trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:

- stage: BuildAndTest
  displayName: Build and Test API

  jobs:
  - job: BuildTest
    steps:

    - checkout: self

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - script: dotnet restore WebCycle/WebCycleApi.csproj
      displayName: 'Restore Api'

    - script: dotnet build WebCycle/WebCycleApi.csproj --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Api'

    - script: >
        dotnet test CycleManager.Tests.Unit/CycleManager.Tests.Unit.csproj 
        --configuration $(buildConfiguration) 
        --no-build
        --logger "trx;LogFileName=test-results.trx"
      displayName: 'Run unit tests'

    - script: |
        echo === Searching for TRX files ===
        dir "$(Build.SourcesDirectory)" /s /b *.trx
      displayName: 'Find TRX files'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        searchFolder: '$(Build.SourcesDirectory)'
        failTaskOnFailedTests: true
        testRunTitle: 'CycleManagerUnit Tests'

- stage: DeployApi
  displayName: Deploy API
  dependsOn: BuildAndTest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  jobs:
  - job: Deploy
    steps:

    - script: >
        dotnet publish WebCycle/WebCycleApi.csproj
        -c $(buildConfiguration)
        -o $(Build.ArtifactStagingDirectory)/api
      displayName: Publish API

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/api'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/api.zip'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'azure-cyclefantasy-prod'
        appName: 'WebCycleApi20250508145015'
        package: '$(Build.ArtifactStagingDirectory)/api.zip'