trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:

- stage: BuildAndTest
  displayName: Build and Test API

  jobs:
  - job: BuildTest
    steps:

    - checkout: self

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - script: dotnet restore WebCycle/WebCycleApi.csproj
      displayName: 'Restore Api'

    - script: dotnet build WebCycle/WebCycleApi.csproj --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Api'

    - script: >
        dotnet build CycleManager.Tests.Unit/CycleManager.Tests.Unit.csproj 
        --configuration $(buildConfiguration) 
      displayName: 'Build unit tests'

    - script: >
        dotnet test CycleManager.Tests.Unit/CycleManager.Tests.Unit.csproj
        --configuration $(buildConfiguration)
        --no-build
        --logger "trx;LogFileName=test-results.trx"
        --collect:"XPlat Code Coverage"
        --settings CodeCoverage.runsettings
      displayName: 'Run unit tests'

    - script: >
        dotnet build CycleManager.Tests.Integration/CycleManager.Tests.Integration.csproj
        --configuration $(buildConfiguration)
      displayName: 'Build integration tests'

    - script: >
        dotnet test CycleManager.Tests.Integration/CycleManager.Tests.Integration.csproj
        --configuration $(buildConfiguration)
        --no-build
        --logger "trx;LogFileName=integration-test-results.trx"
        --collect:"XPlat Code Coverage"
      displayName: 'Run integration tests'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        searchFolder: '$(Build.SourcesDirectory)'
        failTaskOnFailedTests: true
        testRunTitle: 'CycleFantasy Tests'

    - task: PublishCodeCoverageResults@2
      displayName: 'Publish code coverage'
      inputs:
        summaryFileLocation: '$(Build.SourcesDirectory)/**/TestResults/**/coverage.cobertura.xml'
        failIfCoverageEmpty: true

- stage: DeployApi
  displayName: Deploy API
  dependsOn: BuildAndTest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  jobs:
  - job: Deploy
    steps:

    - script: >
        dotnet publish WebCycle/WebCycleApi.csproj
        -c $(buildConfiguration)
        -o $(Build.ArtifactStagingDirectory)/api
      displayName: Publish API

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/api'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/api.zip'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'azure-cyclefantasy-prod'
        appName: 'WebCycleApi20250508145015'
        package: '$(Build.ArtifactStagingDirectory)/api.zip'