trigger:
  branches:
    include:
      - master
      - develop

  paths:
    include:
      - WebCycleManager/**
      - Dockerfile
      - pipelines/management.yml
    
    exclude:
        - README.md
        - docs/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'cyclemanager'
  containerRegistry: 'cyclingregistry123.azurecr.io'
  dockerRegistryServiceConnection: 'cyclingregistry123'
  azureSubscription: 'azure-cyclefantasy-prod'
  resourceGroup: 'rg_cycledb'
  containerAppName: 'cyclingapp'
  tag: '$(Build.BuildId)'

stages:

# =====================================
# Build docker image
# =====================================

- stage: Build
  displayName: Build Management Docker Image

  jobs:
  - job: BuildDocker
    displayName: Build Docker image

    steps:

    # Checkout source
    - checkout: self

    # Build + Push Docker image
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: Dockerfile
        buildContext: .
        tags: |
          $(tag)

    # ==========================================
    # Push + Deploy
    # Alleen op master
    # ==========================================

- stage: Deploy
  displayName: Push and Deploy Management
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  jobs:
  - job: DeployContainerApp
    displayName: Push and Deploy Container App

    steps:

    - checkout: self

    # Build opnieuw omdat deze job op een nieuwe agent draait
    - task: Docker@2
      displayName: 'Build Docker image for deployment'
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: Dockerfile
        buildContext: .
        tags: |
          $(tag)
  
    - task: Docker@2
      displayName: 'Push Docker image to ACR'
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    # Update Azure Container App
    - task: AzureCLI@2
      displayName: 'Deploy Container App'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az containerapp update \
            --name $(containerAppName) \
            --resource-group $(resourceGroup) \
            --image $(containerRegistry)/$(imageRepository):$(tag)
