trigger:
- develop

resources:
  pipelines:
  - pipeline: api
    source: CycleFantasy-API
    trigger:
      branches:
        include:
        - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build WebApp
  
  jobs:
  - job: BuildWeb
    displayName: Build WebApp

    steps:

    - checkout: self

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - script: dotnet restore CycleFantasy.sln
      displayName: 'Restore'

    - script: dotnet build CycleFantasy.sln --configuration $(buildConfiguration) --no-restore
      displayName: 'Build'

    - script: >
        dotnet publish WebApp/WebApp.csproj
        -c $(buildConfiguration)
        -o $(Build.ArtifactStagingDirectory)/web
      displayName: 'Publish WebApp'

    - task: ArchiveFiles@2
      displayName: 'Archive WebApp'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/web'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/web.zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/web.zip'
      artifact: web

- stage: Deploy
  displayName: Deploy WebApp
  dependsOn: Build

  condition: succeeded()

  jobs:
  - job: DeployWeb
    displayName: Deploy WebApp

    steps:

    - download: current
      artifact: web

    - task: AzureWebApp@1
      displayName: 'Deploy WebApp'
      inputs:
        azureSubscription: 'azure-cyclefantasy-prod'
        appName: 'WebApp20250508172648'
        package: '$(Pipeline.Workspace)/web/web.zip'