namespace CycleManager.Services.Helpers
{
    public static class CountryHelper
    {
        public static readonly Dictionary<string, string> Countries =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "AF", "Afghanistan" },
            { "AL", "Albanië" },
            { "DZ", "Algerije" },
            { "AS", "Amerikaans-Samoa" },
            { "AD", "Andorra" },
            { "AO", "Angola" },
            { "AI", "Anguilla" },
            { "AQ", "Antarctica" },
            { "AG", "Antigua en Barbuda" },
            { "AR", "Argentinië" },
            { "AM", "Armenië" },
            { "AW", "Aruba" },
            { "AU", "Australië" },
            { "AT", "Oostenrijk" },
            { "AZ", "Azerbeidzjan" },
            { "BS", "Bahama’s" },
            { "BH", "Bahrein" },
            { "BD", "Bangladesh" },
            { "BB", "Barbados" },
            { "BY", "Wit-Rusland" },
            { "BE", "België" },
            { "BZ", "Belize" },
            { "BJ", "Benin" },
            { "BM", "Bermuda" },
            { "BT", "Bhutan" },
            { "BO", "Bolivia" },
            { "BA", "Bosnië en Herzegovina" },
            { "BW", "Botswana" },
            { "BR", "Brazilië" },
            { "IO", "Brits Indische Oceaanterritorium" },
            { "BN", "Brunei" },
            { "BG", "Bulgarije" },
            { "BF", "Burkina Faso" },
            { "BI", "Burundi" },
            { "KH", "Cambodja" },
            { "CM", "Kameroen" },
            { "CA", "Canada" },
            { "CV", "Kaapverdië" },
            { "KY", "Kaaimaneilanden" },
            { "CF", "Centraal-Afrikaanse Republiek" },
            { "TD", "Tsjaad" },
            { "CL", "Chili" },
            { "CN", "China" },
            { "CX", "Christmaseiland" },
            { "CC", "Cocoseilanden" },
            { "CO", "Colombia" },
            { "KM", "Comoren" },
            { "CG", "Congo-Brazzaville" },
            { "CD", "Congo-Kinshasa" },
            { "CK", "Cookeilanden" },
            { "CR", "Costa Rica" },
            { "CI", "Ivoorkust" },
            { "HR", "Kroatië" },
            { "CU", "Cuba" },
            { "CW", "Curaçao" },
            { "CY", "Cyprus" },
            { "CZ", "Tsjechië" },
            { "DK", "Denemarken" },
            { "DJ", "Djibouti" },
            { "DM", "Dominica" },
            { "DO", "Dominicaanse Republiek" },
            { "EC", "Ecuador" },
            { "EG", "Egypte" },
            { "SV", "El Salvador" },
            { "GQ", "Equatoriaal-Guinea" },
            { "ER", "Eritrea" },
            { "EE", "Estland" },
            { "ET", "Ethiopië" },
            { "FK", "Falklandeilanden" },
            { "FO", "Faeröer" },
            { "FJ", "Fiji" },
            { "FI", "Finland" },
            { "FR", "Frankrijk" },
            { "GF", "Frans-Guyana" },
            { "PF", "Frans-Polynesië" },
            { "GA", "Gabon" },
            { "GM", "Gambia" },
            { "GE", "Georgië" },
            { "DE", "Duitsland" },
            { "GH", "Ghana" },
            { "GI", "Gibraltar" },
            { "GR", "Griekenland" },
            { "GL", "Groenland" },
            { "GD", "Grenada" },
            { "GP", "Guadeloupe" },
            { "GU", "Guam" },
            { "GT", "Guatemala" },
            { "GG", "Guernsey" },
            { "GN", "Guinea" },
            { "GW", "Guinee-Bissau" },
            { "GY", "Guyana" },
            { "HT", "Haïti" },
            { "HN", "Honduras" },
            { "HK", "Hongkong" },
            { "HU", "Hongarije" },
            { "IS", "IJsland" },
            { "IN", "India" },
            { "ID", "Indonesië" },
            { "IR", "Iran" },
            { "IQ", "Irak" },
            { "IE", "Ierland" },
            { "IM", "Isle of Man" },
            { "IL", "Israël" },
            { "IT", "Italië" },
            { "JM", "Jamaica" },
            { "JP", "Japan" },
            { "JE", "Jersey" },
            { "JO", "Jordanië" },
            { "KZ", "Kazachstan" },
            { "KE", "Kenia" },
            { "KI", "Kiribati" },
            { "KW", "Koeweit" },
            { "KG", "Kirgizië" },
            { "LA", "Laos" },
            { "LV", "Letland" },
            { "LB", "Libanon" },
            { "LS", "Lesotho" },
            { "LR", "Liberia" },
            { "LY", "Libië" },
            { "LI", "Liechtenstein" },
            { "LT", "Litouwen" },
            { "LU", "Luxemburg" },
            { "MO", "Macao" },
            { "MK", "Noord-Macedonië" },
            { "MG", "Madagaskar" },
            { "MW", "Malawi" },
            { "MY", "Maleisië" },
            { "MV", "Maldiven" },
            { "ML", "Mali" },
            { "MT", "Malta" },
            { "MH", "Marshalleilanden" },
            { "MQ", "Martinique" },
            { "MR", "Mauritanië" },
            { "MU", "Mauritius" },
            { "YT", "Mayotte" },
            { "MX", "Mexico" },
            { "FM", "Micronesia" },
            { "MD", "Moldavië" },
            { "MC", "Monaco" },
            { "MN", "Mongolië" },
            { "ME", "Montenegro" },
            { "MS", "Montserrat" },
            { "MA", "Marokko" },
            { "MZ", "Mozambique" },
            { "MM", "Myanmar" },
            { "NA", "Namibië" },
            { "NR", "Nauru" },
            { "NP", "Nepal" },
            { "NL", "Nederland" },
            { "NC", "Nieuw-Caledonië" },
            { "NZ", "Nieuw-Zeeland" },
            { "NI", "Nicaragua" },
            { "NE", "Niger" },
            { "NG", "Nigeria" },
            { "NU", "Niue" },
            { "KP", "Noord-Korea" },
            { "MP", "Noordelijke Marianen" },
            { "NO", "Noorwegen" },
            { "OM", "Oman" },
            { "PK", "Pakistan" },
            { "PW", "Palau" },
            { "PS", "Palestina" },
            { "PA", "Panama" },
            { "PG", "Papoea-Nieuw-Guinea" },
            { "PY", "Paraguay" },
            { "PE", "Peru" },
            { "PH", "Filipijnen" },
            { "PL", "Polen" },
            { "PT", "Portugal" },
            { "PR", "Puerto Rico" },
            { "QA", "Qatar" },
            { "RE", "Réunion" },
            { "RO", "Roemenië" },
            { "RU", "Rusland" },
            { "RW", "Rwanda" },
            { "BL", "Saint-Barthélemy" },
            { "SH", "Sint-Helena" },
            { "KN", "Saint Kitts en Nevis" },
            { "LC", "Saint Lucia" },
            { "MF", "Saint-Martin" },
            { "PM", "Saint-Pierre en Miquelon" },
            { "VC", "Saint Vincent en de Grenadines" }
        };

        public static string GetName(string isoCode)
        {
            if (string.IsNullOrWhiteSpace(isoCode)) return string.Empty;
            return Countries.TryGetValue(isoCode.ToUpper(), out var name)
                ? name
                : isoCode; // fallback: gewoon de code teruggeven
        }
    }
}
